name: Go pipeline

on:
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      gocd:
        image: gocd/gocd-server:v23.1.0
        ports:
        - 8153:8513

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Unit test
      run: go test -v ./... -tags=unit
    
    - name: Integration test
      run: go test -v ./... -tags=integration

    - name: Go build
      run: go build -v ./...